"""Read-only catalog for built-in "one map" datasets.

The catalog is generated by ``scripts/ingest_one_map_data.py`` and lives
under ``backend/app/data/builtin/one_map`` so existing ``builtin:`` workflow
sources can load the files without another storage convention.
"""
from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Dict, List

from ..config import AppConfig


JOINABLE_CATALOG_DEFAULTS: Dict[str, Dict[str, str]] = {
    "world_population_by_country": {
        "geometry_source": "world_countries",
        "join_key": "region_code",
    }
}


class OneMapCatalogService:
    def __init__(self, config: AppConfig):
        self.config = config
        self.root = self.config.builtin_dir / "one_map"
        self.catalog_path = self.root / "catalog.json"
        self.missing_path = self.root / "missing_data_requirements.md"

    def list_catalog(self) -> Dict[str, Any]:
        items = self._read_items()
        return {
            "status": "success",
            "path": str(self.catalog_path),
            "items": items,
            "missing_requirements_path": str(self.missing_path),
            "missing_requirements_available": self.missing_path.exists(),
        }

    def get_item(self, dataset_id: str) -> Dict[str, Any]:
        target = str(dataset_id or "").strip()
        for item in self._read_items():
            if item["id"] == target:
                return item
        raise KeyError(f"Unknown one-map dataset: {dataset_id}")

    def resolve_item_path(self, item: Dict[str, Any]) -> Path:
        source = str(item.get("source") or "")
        if not source.startswith("builtin:"):
            raise ValueError(f"Catalog item has no builtin source: {item.get('id')}")
        relative = source[len("builtin:"):].lstrip("/").replace("\\", "/")
        path = (self.config.builtin_dir / relative).resolve()
        path.relative_to(self.config.builtin_dir.resolve())
        if not path.exists():
            raise FileNotFoundError(path)
        return path

    def _read_items(self) -> List[Dict[str, Any]]:
        if not self.catalog_path.exists():
            return []
        try:
            payload = json.loads(self.catalog_path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError):
            return []
        raw_items = payload.get("items", [])
        if not isinstance(raw_items, list):
            return []
        return [self._normalize_item(item) for item in raw_items if isinstance(item, dict)]

    def _normalize_item(self, item: Dict[str, Any]) -> Dict[str, Any]:
        source = str(item.get("source") or "")
        if source and not source.startswith("builtin:"):
            source = f"builtin:{source.lstrip('/')}"
        dataset_id = str(item.get("id") or source or "unknown")
        join_defaults = JOINABLE_CATALOG_DEFAULTS.get(dataset_id, {})
        fields = item.get("fields")
        if not isinstance(fields, list):
            fields = []
        tags = item.get("tags")
        if not isinstance(tags, list):
            tags = []
        return {
            "id": dataset_id,
            "name": str(item.get("name") or item.get("id") or source or "Untitled dataset"),
            "category": str(item.get("category") or "other"),
            "source": source,
            "format": str(item.get("format") or ""),
            "geometry_source": str(item.get("geometry_source") or join_defaults.get("geometry_source") or ""),
            "join_key": str(item.get("join_key") or join_defaults.get("join_key") or ""),
            "fields": [str(field) for field in fields],
            "coverage": str(item.get("coverage") or ""),
            "source_year": str(item.get("source_year") or ""),
            "source_name": str(item.get("source_name") or ""),
            "source_url": str(item.get("source_url") or ""),
            "license": str(item.get("license") or ""),
            "includes_taiwan": bool(item.get("includes_taiwan")),
            "status": str(item.get("status") or "unknown"),
            "geometry_type": str(item.get("geometry_type") or ""),
            "recommended_template": str(item.get("recommended_template") or ""),
            "population_fields": [str(field) for field in item.get("population_fields", []) if isinstance(field, str)],
            "tags": [str(tag) for tag in tags],
            "description": str(item.get("description") or ""),
            "style_field": str(item.get("style_field") or ""),
        }
